DROP TABLE RESERVATION_ITEM;
DROP TABLE RESERVATION_REVIEW;
DROP TABLE RESERVATION;
DROP TABLE LEPORTS_ITEM;
DROP TABLE LEPORTS;
DROP TABLE CUSTOMER_SUPPORT;
DROP TABLE CUSTOMER_QUESTION;
DROP TABLE TRADE_COMMENTS;
DROP TABLE TRADE;
DROP TABLE PARTNER;
DROP TABLE MEMBER;
DROP SEQUENCE MEMBER_SEQ;
DROP SEQUENCE SUPPORT_SEQ;
DROP SEQUENCE CUSTOMER_QUESTION_SEQ;
DROP SEQUENCE TRADE_COMMENT_SEQ;
DROP SEQUENCE TRADE_SEQ;
DROP SEQUENCE LEPORTS_SEQ;
DROP SEQUENCE PARTNER_SEQ;
DROP SEQUENCE LEPORTS_ITEM_SEQ;
DROP SEQUENCE RS_REVIEW_SEQ;
DROP SEQUENCE RS_ITEM_SEQ;
DROP SEQUENCE RESERVATION_SEQ;
CREATE TABLE MEMBER
(
    USER_ID        VARCHAR2(4000) PRIMARY KEY,
    USER_NAME      VARCHAR2(4000) NOT NULL,
    USER_EMAIL     VARCHAR2(4000) NOT NULL,
    USER_PW        VARCHAR2(4000) NOT NULL,
    SALT           VARCHAR2(4000) NOT NULL,
    USER_VERIFY    NUMBER(1,0) DEFAULT 0,
    PARTNER_VERIFY NUMBER(1,0) DEFAULT 0,
    ADMIN_VERIFY   NUMBER(1,0) DEFAULT 0
);
CREATE TABLE PARTNER
(
    PARTNER_ID           VARCHAR2(4000) PRIMARY KEY,
    USER_ID              VARCHAR2(4000) NOT NULL,
    C_NAME               VARCHAR2(4000) NOT NULL,
    C_POSTNUM            VARCHAR2(4000) NOT NULL,
    C_ADDRESS            VARCHAR2(4000) NOT NULL,
    C_DETAIL_ADDRESS     VARCHAR2(4000) NOT NULL,
    C_PHONE              VARCHAR2(4000) NOT NULL,
    PARTNER_LICENSE_NUM  VARCHAR2(4000) NOT NULL,
    PARTNER_LICENSE_DOCS VARCHAR2(4000) NOT NULL,
    CONSTRAINT FK_PARTNER_USER_ID FOREIGN KEY (USER_ID)
        REFERENCES MEMBER (USER_ID) ON DELETE CASCADE
);
CREATE TABLE LEPORTS
(
    LEPORTS_ID       VARCHAR2(4000) PRIMARY KEY,
    PARTNER_ID       VARCHAR2(4000) NOT NULL,
    LEPORTS_TITLE    VARCHAR2(4000) NOT NULL,
    LEPORTS_TYPE     VARCHAR2(4000) NOT NULL,
    LEPORTS_LOC      VARCHAR2(4000) NOT NULL,
    LEPORTS_REGIDATE DATE DEFAULT SYSDATE NOT NULL,
    LEPORTS_MAIN_IMG VARCHAR2(4000) NOT NULL,
    LEPORTS_SUB_IMG1 VARCHAR2(4000),
    LEPORTS_SUB_IMG2 VARCHAR2(4000),
    LEPORTS_SUB_IMG3 VARCHAR2(4000),
    LEPORTS_SUB_IMG4 VARCHAR2(4000),
    LEPORTS_CONTENT  VARCHAR2(4000) NOT NULL,
    REVIEW_STAR      NUMBER(2,1) DEFAULT 0,
    RESERVE_CNT      NUMBER(8,0) DEFAULT 0,
    REVIEW_CNT       NUMBER(8,0) DEFAULT 0,
    CONSTRAINT FK_LEPORTS_PARTNER_ID FOREIGN KEY (PARTNER_ID)
        REFERENCES PARTNER (PARTNER_ID) ON DELETE CASCADE
);
CREATE TABLE LEPORTS_ITEM
(
    LEPORTS_ITEM_ID      VARCHAR2(4000) PRIMARY KEY,
    LEPORTS_ID           VARCHAR2(4000) NOT NULL,
    LEPORTS_ITEM_TITLE   VARCHAR2(4000) NOT NULL,
    LEPORTS_SUMMARY      VARCHAR2(4000) NOT NULL,
    LEPORTS_PRICE        NUMBER(8,0) NOT NULL,
    LEPORTS_MAX_CAPACITY NUMBER(8,0) NOT NULL,
    CONSTRAINT FK_LEPORTS_ITEM_LEPORTS_ID FOREIGN KEY (LEPORTS_ID)
        REFERENCES LEPORTS (LEPORTS_ID) ON DELETE CASCADE
);
CREATE TABLE RESERVATION
(
    RESERVATION_ID  VARCHAR2(4000) PRIMARY KEY,
    USER_ID         VARCHAR2(4000) NOT NULL,
    LEPORTS_ID      VARCHAR2(4000) NOT NULL,
    RS_NAME         VARCHAR2(4000) NOT NULL,
    RS_PHONE        VARCHAR2(4000) NOT NULL,
    RS_PERSONS      VARCHAR2(4000) NOT NULL,
    RS_PAYMETHOD    VARCHAR2(4000) NOT NULL,
    RS_DATE         VARCHAR2(4000) NOT NULL,
    RS_PAYMENT_DATE DATE DEFAULT SYSDATE NOT NULL,
    RS_PRICE        NUMBER(8, 0) NOT NULL,
    RS_ITEM_NAME    VARCHAR2(4000) NOT NULL,
    TID             VARCHAR2(4000),
    REVIEW_VERIFY   NUMBER(1, 0) DEFAULT 0,
    CONSTRAINT FK_RS_LEPORTS_ID FOREIGN KEY (LEPORTS_ID)
        REFERENCES LEPORTS (LEPORTS_ID) ON DELETE CASCADE,
    CONSTRAINT FK_RS_USER_ID FOREIGN KEY (USER_ID)
        REFERENCES MEMBER (USER_ID) ON DELETE CASCADE
);
CREATE TABLE RESERVATION_ITEM
(
    RS_ITEM_ID      VARCHAR2(4000) PRIMARY KEY,
    RESERVATION_ID  VARCHAR2(4000) NOT NULL,
    LEPORTS_ITEM_ID VARCHAR2(4000) NOT NULL,
    RS_ITEM_TITLE   VARCHAR2(4000),
    RS_ITEM_PERSON  NUMBER(8, 0),
    RS_ITEM_PRICE   NUMBER(8, 0),
    CONSTRAINT FK_RESERVATION_ID FOREIGN KEY (RESERVATION_ID)
        REFERENCES RESERVATION (RESERVATION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_LEPORTS_ITEM_ID FOREIGN KEY (LEPORTS_ITEM_ID)
        REFERENCES LEPORTS_ITEM (LEPORTS_ITEM_ID) ON DELETE CASCADE
);
CREATE TABLE RESERVATION_REVIEW
(
    REVIEW_ID       VARCHAR2(4000) PRIMARY KEY,
    LEPORTS_ID      VARCHAR2(4000) NOT NULL,
    RESERVATION_ID  VARCHAR2(4000) NOT NULL,
    USER_ID         VARCHAR2(4000) NOT NULL,
    REVIEW_COMMENTS VARCHAR2(4000) NOT NULL,
    REVIEW_REGIDATE DATE DEFAULT SYSDATE NOT NULL,
    REVIEW_STAR     NUMBER(1, 0) NOT NULL,
    CONSTRAINT FK_REVIEW_LEPORTS_ID FOREIGN KEY (LEPORTS_ID)
        REFERENCES LEPORTS (LEPORTS_ID) ON DELETE CASCADE,
    CONSTRAINT FK_REVIEW_RESERVATION_ID FOREIGN KEY (RESERVATION_ID)
        REFERENCES RESERVATION (RESERVATION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_REVIEW_USER_ID FOREIGN KEY (USER_ID)
        REFERENCES MEMBER (USER_ID) ON DELETE CASCADE
);
CREATE TABLE TRADE
(
    TRADE_ID        VARCHAR2(4000) PRIMARY KEY,
    USER_ID         VARCHAR2(4000) NOT NULL,
    TRADE_MAIN_IMG  VARCHAR2(4000) NOT NULL,
    TRADE_SUB_IMG1  VARCHAR2(4000),
    TRADE_SUB_IMG2  VARCHAR2(4000),
    TRADE_SUB_IMG3  VARCHAR2(4000),
    TRADE_SUB_IMG4  VARCHAR2(4000),
    TRADE_TITLE     VARCHAR2(4000) NOT NULL,
    TRADE_CONTENTS  VARCHAR2(4000) NOT NULL,
    TRADE_TYPE      VARCHAR2(4000) NOT NULL,
    TRADE_LOC       VARCHAR2(4000) NOT NULL,
    TRADE_PHONE     VARCHAR2(4000) NOT NULL,
    TRADE_USER_NAME VARCHAR2(4000) NOT NULL,
    TRADE_PRICE     NUMBER(8,0) NOT NULL,
    TRADE_REGIDATE  DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_TRADE_USER_ID FOREIGN KEY (USER_ID)
        REFERENCES MEMBER (USER_ID) ON DELETE CASCADE
);
CREATE TABLE TRADE_COMMENTS
(
    TRADE_COMMENT_ID    VARCHAR2(4000) PRIMARY KEY,
    TRADE_ID            VARCHAR2(4000) NOT NULL,
    USER_ID             VARCHAR2(4000) NOT NULL,
    TRADE_COMMENT       VARCHAR2(4000) NOT NULL,
    COMMENT_REGIDATE    DATE   DEFAULT SYSDATE NOT NULL,
    TRADE_COMMENT_LEVEL VARCHAR2(4000) NOT NULL,
    TRADE_DEPTH         NUMBER DEFAULT 0       NOT NULL,
    CONSTRAINT FK_TRADE_COMMENTS_TRADE_ID FOREIGN KEY (TRADE_ID)
        REFERENCES TRADE (TRADE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_TRADE_COMMENTS_USER_ID FOREIGN KEY (USER_ID)
        REFERENCES MEMBER (USER_ID) ON DELETE CASCADE
);
CREATE TABLE CUSTOMER_QUESTION
(
    QUESTION_ID      VARCHAR2(4000) PRIMARY KEY,
    USER_ID          VARCHAR2(4000) NOT NULL,
    Q_TITLE          VARCHAR2(4000),
    Q_TYPE           VARCHAR2(4000),
    Q_CONTENT        VARCHAR2(4000),
    Q_RESERVATION_ID VARCHAR2(4000),
    Q_PHONE          VARCHAR2(4000),
    Q_REGIDATE       DATE DEFAULT SYSDATE NOT NULL,
    ANSWER_VERIFY    NUMBER(1,0) DEFAULT 0,
    USER_EMAIL       VARCHAR2(4000),
    USER_NAME        VARCHAR2(4000),
    QUESTION_GROUP   VARCHAR2(4000),
    CONSTRAINT FK_CUSTOMER_QUESTION_USER_ID FOREIGN KEY (USER_ID)
        REFERENCES MEMBER (USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_CUSTOMER_QUESTION_ID_GROUP FOREIGN KEY (QUESTION_GROUP)
        REFERENCES CUSTOMER_QUESTION (QUESTION_ID) ON DELETE CASCADE
);
CREATE TABLE CUSTOMER_SUPPORT
(
    SUPPORT_ID VARCHAR2(4000) PRIMARY KEY,
    S_TYPE     VARCHAR2(4000) NOT NULL,
    S_QUESTION VARCHAR2(4000) NOT NULL,
    S_ANSWER   VARCHAR2(4000) NOT NULL
);
CREATE SEQUENCE MEMBER_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
CREATE SEQUENCE RESERVATION_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
CREATE SEQUENCE RS_ITEM_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
CREATE SEQUENCE RS_REVIEW_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
CREATE SEQUENCE PARTNER_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LEPORTS_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LEPORTS_ITEM_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TRADE_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
CREATE SEQUENCE TRADE_COMMENT_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
CREATE SEQUENCE CUSTOMER_QUESTION_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
CREATE SEQUENCE SUPPORT_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

CREATE
OR REPLACE FUNCTION RSITEMSEQ
RETURN NUMBER
IS
BEGIN
RETURN RS_ITEM_SEQ.NEXTVAL;
END;
/
